export function getRowGap(number?: number): string {
  switch (number) {
    case 1:
      return 'gap-y-px';
    case 2:
      return 'gap-y-0.5';
    case 3:
      return 'gap-y-1';
    case 4:
      return 'gap-y-1';
    case 5:
      return 'gap-y-1';
    case 6:
      return 'gap-y-1.5';
    case 7:
      return 'gap-y-1.5';
    case 8:
      return 'gap-y-2';
    case 9:
      return 'gap-y-2';
    case 10:
      return 'gap-y-2.5';
    case 11:
      return 'gap-y-2.5';
    case 12:
      return 'gap-y-3';
    case 13:
      return 'gap-y-3';
    case 14:
      return 'gap-y-3';
    case 15:
      return 'gap-y-3';
    case 16:
      return 'gap-y-4';
    case 17:
      return 'gap-y-4';
    case 18:
      return 'gap-y-4';
    case 19:
      return 'gap-y-4';
    case 20:
      return 'gap-y-5';
    case 21:
      return 'gap-y-5';
    case 22:
      return 'gap-y-5';
    case 23:
      return 'gap-y-5';
    case 24:
      return 'gap-y-6';
    case 25:
      return 'gap-y-6';
    case 26:
      return 'gap-y-6';
    case 27:
      return 'gap-y-6';
    case 28:
      return 'gap-y-7';
    case 29:
      return 'gap-y-7';
    case 30:
      return 'gap-y-7';
    case 31:
      return 'gap-y-7';
    case 32:
      return 'gap-y-8';
    default:
      return 'gap-y-0';
  }
}
