export function getGridTemplateColumn(number?: number, screens?: string): string {
  if (!screens) {
    switch (number) {
      case 1:
        return 'grid-cols-1';
      case 2:
        return 'grid-cols-2';
      case 3:
        return 'grid-cols-3';
      case 4:
        return 'grid-cols-4';
      case 5:
        return 'grid-cols-5';
      case 6:
        return 'grid-cols-6';
      case 7:
        return 'grid-cols-7';
      case 8:
        return 'grid-cols-8';
      case 9:
        return 'grid-cols-9';
      case 10:
        return 'grid-cols-10';
      case 11:
        return 'grid-cols-11';
      case 12:
        return 'grid-cols-12';
      default:
        return 'grid-cols-0';
    }
  }

  switch (`${screens}:${number}`) {
    case 'xs:1':
      return 'grid-cols-1';
    case 'xs:2':
      return 'grid-cols-2';
    case 'xs:3':
      return 'grid-cols-3';
    case 'xs:4':
      return 'grid-cols-4';
    case 'xs:5':
      return 'grid-cols-5';
    case 'xs:6':
      return 'grid-cols-6';
    case 'xs:7':
      return 'grid-cols-7';
    case 'xs:8':
      return 'grid-cols-8';
    case 'xs:9':
      return 'grid-cols-9';
    case 'xs:10':
      return 'grid-cols-10';
    case 'xs:11':
      return 'grid-cols-11';
    case 'xs:12':
      return 'grid-cols-12';
    case 'sm:1':
      return 'sm:grid-cols-1';
    case 'sm:2':
      return 'sm:grid-cols-2';
    case 'sm:3':
      return 'sm:grid-cols-3';
    case 'sm:4':
      return 'sm:grid-cols-4';
    case 'sm:5':
      return 'sm:grid-cols-5';
    case 'sm:6':
      return 'sm:grid-cols-6';
    case 'sm:7':
      return 'sm:grid-cols-7';
    case 'sm:8':
      return 'sm:grid-cols-8';
    case 'sm:9':
      return 'sm:grid-cols-9';
    case 'sm:10':
      return 'sm:grid-cols-10';
    case 'sm:11':
      return 'sm:grid-cols-11';
    case 'sm:12':
      return 'sm:grid-cols-12';
    case 'md:1':
      return 'md:grid-cols-1';
    case 'md:2':
      return 'md:grid-cols-2';
    case 'md:3':
      return 'md:grid-cols-3';
    case 'md:4':
      return 'md:grid-cols-4';
    case 'md:5':
      return 'md:grid-cols-5';
    case 'md:6':
      return 'md:grid-cols-6';
    case 'md:7':
      return 'md:grid-cols-7';
    case 'md:8':
      return 'md:grid-cols-8';
    case 'md:9':
      return 'md:grid-cols-9';
    case 'md:10':
      return 'md:grid-cols-10';
    case 'md:11':
      return 'md:grid-cols-11';
    case 'md:12':
      return 'md:grid-cols-12';
    case 'lg:1':
      return 'lg:grid-cols-1';
    case 'lg:2':
      return 'lg:grid-cols-2';
    case 'lg:3':
      return 'lg:grid-cols-3';
    case 'lg:4':
      return 'lg:grid-cols-4';
    case 'lg:5':
      return 'lg:grid-cols-5';
    case 'lg:6':
      return 'lg:grid-cols-6';
    case 'lg:7':
      return 'lg:grid-cols-7';
    case 'lg:8':
      return 'lg:grid-cols-8';
    case 'lg:9':
      return 'lg:grid-cols-9';
    case 'lg:10':
      return 'lg:grid-cols-10';
    case 'lg:11':
      return 'lg:grid-cols-11';
    case 'lg:12':
      return 'lg:grid-cols-12';
    case 'xl:1':
      return 'xl:grid-cols-1';
    case 'xl:2':
      return 'xl:grid-cols-2';
    case 'xl:3':
      return 'xl:grid-cols-3';
    case 'xl:4':
      return 'xl:grid-cols-4';
    case 'xl:5':
      return 'xl:grid-cols-5';
    case 'xl:6':
      return 'xl:grid-cols-6';
    case 'xl:7':
      return 'xl:grid-cols-7';
    case 'xl:8':
      return 'xl:grid-cols-8';
    case 'xl:9':
      return 'xl:grid-cols-9';
    case 'xl:10':
      return 'xl:grid-cols-10';
    case 'xl:11':
      return 'xl:grid-cols-11';
    case 'xl:12':
      return 'xl:grid-cols-12';
    default:
      return 'grid-cols-0';
  }
}
