export function getGridGap(number?: number): string {
  switch (number) {
    case 1:
      return 'gap-px';
    case 2:
      return 'gap-0.5';
    case 3:
      return 'gap-1';
    case 4:
      return 'gap-1';
    case 5:
      return 'gap-1';
    case 6:
      return 'gap-1.5';
    case 7:
      return 'gap-1.5';
    case 8:
      return 'gap-2';
    case 9:
      return 'gap-2';
    case 10:
      return 'gap-2.5';
    case 11:
      return 'gap-2.5';
    case 12:
      return 'gap-3';
    case 13:
      return 'gap-3';
    case 14:
      return 'gap-3';
    case 15:
      return 'gap-3';
    case 16:
      return 'gap-4';
    case 17:
      return 'gap-4';
    case 18:
      return 'gap-4';
    case 19:
      return 'gap-4';
    case 20:
      return 'gap-5';
    case 21:
      return 'gap-5';
    case 22:
      return 'gap-5';
    case 23:
      return 'gap-5';
    case 24:
      return 'gap-6';
    case 25:
      return 'gap-6';
    case 26:
      return 'gap-6';
    case 27:
      return 'gap-6';
    case 28:
      return 'gap-7';
    case 29:
      return 'gap-7';
    case 30:
      return 'gap-7';
    case 31:
      return 'gap-7';
    case 32:
      return 'gap-8';
    case 36:
      return 'gap-9';
    default:
      return `gap-[${number}px]`;
  }
}
