mutation destroyUserAddress($id: ID!) {
  destroyUserAddress(input: {id: $id}) {
    id
    user {
      id
      userAddresses(first: 10) {
        nodes {
          ...userAddress
        }
      }
    }
  }
}
