mutation topUpGiftCard($code: String!) {
  topUpGiftCard(input: {code: $code}) {
    id
    amount
    redeemer {
      id
      wallet
      currentOrder{
        id
        usableStoreCredit
      }
    }
  }
}
